# Generated by Django 2.1.3 on 2018-11-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='media', verbose_name='Imágen')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=245)),
                ('fecha_n', models.DateField()),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota_Adoptante',
            fields=[
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Mascota')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoUser'),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo_viv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vivienda'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raza'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='mascota_adoptante',
            name='id_socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Socio'),
        ),
    ]
